### ISSUE TITLE
Zoom graph

### ISSUE THREAD

**Issue by rafariva** [sirmordred/WhatsCloud-Tracker#2]
Hi, the charts cant zoom it, the letter are to tiny

**Comment by sirmordred** [comment]
I'm using 3rd party lib for charts and graphs but yeah texts are too tiny, will try to solve it on next version

Thanx 👍

**Comment by sirmordred** [comment]
Ok, released new version (2.0) I increased the font size of texts on charts and graphs, should be good now
Thanx again for the feedback 👍
