### ISSUE TITLE
Total words count

### ISSUE THREAD

**Issue by AlemanSantos** [sirmordred/WhatsCloud-Tracker#6]
Hi! Please add a Total words count, like the Total message count. With this we can see more accurately who writes more! Even if other person have more messages but shorter.

**Comment by sirmordred** [comment]
Good idea 👍  Marked as "Enhancement"

Thanx 👍

**Comment by sirmordred** [comment]
Ok, the requested feature has been implemented in version 2.0, thanx again for the feedbacks 👍
